name: release

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@v3.6.0
      with:
        node-version: 14
    - name: Archive Release
      uses: thedoctor0/zip-release@0.7.1
      with:
        type: 'zip'
        filename: 'VCCModelTemplate.zip'
        exclusions: '*.git* /*node_modules/* .editorconfig'
        
    - uses: plutotcool/release@v1
      with:
        github_token:  ${{ secrets.GITHUB_TOKEN }}
        npm_token: ${{ secrets.NPM_TOKEN }}
